### ISSUE TITLE
Nitpick about Swift

### ISSUE THREAD

**Issue by Longhanks** [artemis-project/artemis-project.github.io#4]
While reading your newest blog post I stumbled about some things concerning Swift that are misleading:

- According to your blog post, Swift uses garbage collection. This is not true: The Swift compiler implements [automatic reference counting,](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html) but at runtime there never is a gargbage collector (although the term might be misleading - see [Chris Lattner's explanation](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160208/009422.html)).
- According to your blog post, "[Swift] does not allow the programmer to use pointers or do unsafe memory operations" - this is wrong, too. Swift allows using pointers, bitcasts and memory rebounds. A great introduction to interacting with C in Swift can be found [here](https://www.raywenderlich.com/148569/unsafe-swift).

**Comment by ubunturox104** [comment]
Thank you for bringing up these issues; I have the errors fixed as necessary, as well as cleaned up some grammatical errors.
